resolver: lts-17.8

packages:
  - .

flags:
  xmobar:
    all_extensions: true

extra-deps:
  - github: jaor/xmobar
    commit: master
  - netlink-1.1.1.0@sha256:d83424b5ba9921191449e4b1f53c7cba7f4375f2c55a9b737c77e982e1f40d00,3689
