name:
    xmonad-private

dependencies:
    - base >= 4.7 && < 5
    - xmonad >= 0.17.0
    - xmonad-contrib >= 0.17.0
    - X11
    - containers
    - flow
    - process
    - unix
    - split
    - utf8-string
    - stm
    - xmobar >= 0.40

library:
    source-dirs: .

executables:
  xmonad-private:
    main:              xmonad.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-private
