resolver: lts-17.8

packages:
  - .
extra-deps:
  - github: xmonad/xmonad
    commit: master
  - git: /home/yecinem/xmonad-contrib/
    commit: ac920b7470eb45915c7b353fad66fe570c4cb2a6
  - github: xmonad/x11
    commit: master
